language: node_js
node_js:
- 10

env:
  global:
  - secure: iIixYkzTe7qojJsubRYlEopmG11VXRUe+vpIQ3fV533zooHj/v2EM2QWuVx4iaxjL1AH5+zVeR9a5PkX8DuyJmvTUM5iat2k5PCw2yY50lVu09v/05WgSwUIoNKmhT5CMEsdBuVEItCtXkCyUXPoop3kgYRu2NmIckxWaJPagQFe/oj2IxhL4UDINXAEMP/LBCpVdbnzXSUZ2USaP9KH6EhBPqTn5wlOmbko+t4e15WO/CiAVhutCvjqBvd8z3BznCGRAfkE8sJN3klxppW3+H4dfJCc4qWyJMAR/zgjuusvyBOpl/+3w/Pi3Uo9QqyGz7KFsJ9hTSDM+F4rDBYOc2w7wXOiMVj/fS3VIWqgnmZSJq+ReYjsN9O2T79pdok1+JqExPAyk4E6lPWFOg/va2bdoxZ6XQ7heWa7f+RUzudU40ZPuqkff9H2wM4tiXoaXhK9fIeIlqpCXlLr2+GCE/oGHBBpP6a/ErB1NDon0n1XHc3kAAK24ij9UW8JRuhVS6K2p6+Rp4+mwgf/eeVZc0ocjqOCIpdvgc7SpTKXh65G9YCKJp5Wey6UmVrQAh4qpjuSj0qr7tUaGjaXYGioIo8K7KQ7Z0XQbzt3M+FDqGv5BR0Azp/q8QVb2DGGJxH6MMh8XJ4NspfKNbBzMicxkiqsbBwDdOW1pK6Go394zxM=
  - secure: Vy+F73lf6J6C14HET998EbKrKyDrgvQngG5Kn32Aeqyoz5RSWcNN5gAhTI+SFKO1zv1M7T/F0Jp5bXa/0IjtYy3RWlLXpDWkXWr25e63MmHgR6EjDOG7u3BxxvhOXDgdVJPHw3q1y3RtlexOfz1f0gRjTv8ZHmB2wae9WTn8yE1KKrDLypvM+agbICQ+bGHce4PMV3jEd5tB17INGZsgLDE779Cxo6rVUAdAmMYOZzAPjyRlHfAbsnf4kI9b259FRK9xtZqaeIKKY2IlmRQ3qv8V6a68AiRHxmvfYUV5EdkZvNIc9BVJauJ0CyZ6CF6xkLEHOpY3/7XdyLUvffh+geevpoirwHsYLIHx/7yDt+1FFPAPiUrr33PFXTZ08dkbWanY7+aDZmQBco5SuMiivo09YOzVXMjAJa36rwIFzyPu3+l9ZWmk81O35sKJse8/DQ23EphpK1UUQNxmx/ySibB7uv5D3XHyoRPR4fEsBDBC7p8IthQ0LSeialjGbQcfbHGWbaMQsS1bgv72II7Hta5Kfm36i9EdW1YCfDQQLTtcOAEW6sNV69A+13opS7q6mKuBa2H1dF5ol7HsqL6dRwaQl5j+HjX789qhtY8Rw6sOnlJJXaYVM7Ju0Px3D8KGxNfTnMy/gQLu3FPSqRHWHYYtWgD7mxhp6lxCe+ubXUQ=
  - secure: e18Dwpe+e4zS7TEQqdT6/WxHiTQGeVjqF6NwkcchpSyn9Coh4oKU6KY31m8ZbgjrIZdPms+6Ztur8fssSThdLg3n2MbxKbujxWZgGF2dIgFGwo9op7UYmSfHdfupsn5679a5ZxQKkbgirE3iL6zXXEjVgi3RBea/n8YtScjEAr81o3qRZr01m0t5ZO17aRaaIyNxjc/Wf4+KrEnTtIwrezfSsHXIuyuNJs6nJdhqh6/G3swDXrMu802Opgyoo+gR9FHott7GJOd2ZFoV/N3bj6P4EUoTWqFuisimZWek0ZfhlBBunU8qQdnKqrqvXkWwHIhgRUeDprP3bonDm/vKCi4u19fy0FO1DAZYwYLHVDa8ONg87jjQKOwVKtt2P2q7KX9Y2s2b2DrAFDe7fcTKoa2+Sojf0Mn3/0yAgJZs1pBpgzkG5AqvMW2ZsWggPAzs7TzzN7qmVVYcAmCgwcbPPS41ysJPXWuwUtaySx6vy9P2zV2QR2vGwL7ZiDnm9N8rMjR9tgQtTnZOqElkpGxYF4eIImGViyMER9Pgv1rQ6XcrxRdSdlxW/BL+FtHq8DuwUDuStMk99OSJTPv3m4XsbxHOBYo4AmhoYcYLu6mRipAIHHKkCknTOePjtQdvr1grcZwaLuFIW1usMv1Mq0yW5SsFvMSPDI6uV3vUe8vY0kY=
  - secure: J/+6jnzb6FQLJKUddKkJJQ8afNOm6x96a1AiQ0MFArwkGlDYDmTqMEDyPwe/62MmrydfXpVDijwswBZo1eHaWmZKRer+6SVOXRtleB2F0bHOzHJbsiGMpacsSZfFOhK/34irRd/EZrKXHL3SJpD7i7QT/gyv3GUTudMrQROpz004jgtE4jf3U/OjTSl4ioWu4nOA1pWpkZ4iuUB807s5mUfWyk0oAU47rbqLJ/H8eH8Ns5oXA0pCtbFwKovH3AIOfLK2gzHS91vBGwr/gQ3BMukbBlrl+RIvgANoPSGOahgFzB9x8w4I7Vw5IjAEtsY8GUxDtt3gm0kQFutDwLLu/22nRUdHJZU7G729WYSqM18jFqMhAraRBp9QU70JojZbxpEvLM1KUML6kbULbiG1oifE1Xc3ODbBVFZ3mKtG8M/iNzfuOxAmMUbWD5f1YZrNsBeqhBT7KpYbwj8Gz+bRYbfCh43/KrEAh/iUyekHN14Wpna9uXcDxSdnnx3dCqfShC0oGH6xND2EVgQujHpwZD347UFicilxGJkMjY0IRtB2jqgJ2sFUIEBGlDg4Iy8dmV90XeClWOX0J8b71wEnegw2mo38jPG5444X8MSGV20mW2HD3UwY5WPUFVs/hdsE2hYHYkKLpXlQ5MWkYOAI0W9WxU1clQyqWg9mg1W2ygA=

install:
- npm install

script:
- npm run lint:no-fix
# - npm run test

after_success:
- sh scripts/travis-push-i18n-keys.sh
- sh scripts/travis-publish-images.sh

before_deploy:
- npm run build:github

# deploy to github pages on master
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
